### ISSUE TITLE
Ability to push data to dataverse

### ISSUE THREAD

**Issue by SteffenBrinckmann** [PASTA-ELN/pasta-eln#10]
Can we push a project (incl. and excl. the hidden items) to the data@fz-juelich?
- There must be menu item to be added "Export to dataverse" to the First Menu Group
- An extra step of cleanup should be implemented: Additional feature to be defined
- Dialog to be shown to enter the API Token (Also provide the instruction to generate the token)
- Initial trial, the dialog needs to be shown and token must be saved internally and used subsequently
- Once when the login is successful, another dialog should be displayed which allows user to pick the data to be archived
- Dialog should be displayed with a list of projects
- User should be able to select and un-select sub-items  within the project also (Samples, Measurements etc)
- All the unassigned items should be listed as part of an unassigned project
- After successful export PID will be assigned to respective projects exported from PASTA
-

**Comment by SteffenBrinckmann** [comment]
URL: https://data.fz-juelich.de/ is the official service, they also have a demo server for testing
Contact person: Oliver Bertuch <o.bertuch@fz-juelich.de>
Pasta would have a menu item below export that says "push to" which opens a dialog / multiple dialogs where the user (to be discussed) can:
- select the data exported (measurements, samples ...) af if hidden items be included too
- gives additional metadata information that data requires

**Comment by jmurugan-fzj** [comment]
Helpful URLs:
- https://data.fz-juelich.de/guide/api/intro.html#what-is-an-api
- https://github.com/IQSS/dataverse

**Comment by jmurugan-fzj** [comment]
@HTsybenko Most of the features associated with this feature has been finalized with latest merge: [303](https://github.com/PASTA-ELN/pasta-eln/pull/303). Please go ahead and test this feature and provide me the feedback.

**Comment by HTsybenko** [comment]
@jmurugan-fzj I guess the changes did not make it to the latest release, so I will start testing as soon as it is available.

**Comment by SteffenBrinckmann** [comment]
In the works; nothing in here to save
