### ISSUE TITLE
Rendering in projects

### ISSUE THREAD

**Issue by SteffenBrinckmann** [PASTA-ELN/pasta-eln#105]
- Rendering of procedures in projectLeafRenderer (what happens if leaf has low width (eg. 200px): then the content is displayed badly)
- Rendering of project details: long comments look awkward

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann I do not understand the way to reproduce this issue, Could you please write the simple steps to do so? So that I can verify the related PR!

**Comment by SteffenBrinckmann** [comment]
- change (make it small) the size of the PASTA-window with the project view: hierarchy. Now there should not be a strange procedure flying in an inappropriate area.
- import the elabFTW: in the project view at the top, the lines should not be too long anymore

**Comment by SteffenBrinckmann** [comment]
The clipping is supposed to be 50px from the end. I guess, in your case you asked PASTA to render it, and then you made it larger; it then does no reevaluate the new width. If you click on that project, it re-renders it correctly. Yes, but clipping is the intended thing.

**Comment by jmurugan-fzj** [comment]
> The clipping is supposed to be 50px from the end. I guess, in your case you asked PASTA to render it, and then you made it larger; it then does no reevaluate the new width. If you click on that project, it re-renders it correctly. Yes, but clipping is the intended thing.

@SteffenBrinckmann 
Are you sure, that clipping is the intended behavior? I would prefer it to be wrapped if possible!

**Comment by SteffenBrinckmann** [comment]
Clipping is intended by the person implementing it as it is easy. Wrapping would require a more complicated algorithm as suddenly each item can have multiple rows.
Yes, it is clipped 50px from the end of the window: it clips what fits into the window. The text can be much longer.

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Ahh Okay, so is there  any means for the user to view/edit the complete textual information?

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj Currently not, there is an old open issue on improving the form #11, there we can think about it. 
Anyhow, it can really only happen for imported data from another ELN that we don't fully understand.

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Okay if this is already documented as part of another story this should be fine, I shall approve this PR now!

**Comment by HTsybenko** [comment]
@SteffenBrinckmann  
- As this issue touches on the topic of rendering for low width, ideally, titles of items, tags, and comments should not overlap when rescaling the window.

![Screenshot from 2023-10-30 10-07-28](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/11efcc35-ad69-40da-a8eb-b71ae3f6ac5c)

- Clipping the text in the project header also prohibits from resizing the window width below the width of it - another reason why this solution is not fully optimal.

**Comment by SteffenBrinckmann** [comment]
To repair
- Copy paste will be part of next version
- Resize to small width, look ugly

**Comment by SteffenBrinckmann** [comment]
@HTsybenko can you please check if this is still an issue:
- we can prevent small window sizes and large image size combinations
