### ISSUE TITLE
Bug if branch not in doc

### ISSUE THREAD

**Issue by jmurugan-fzj** [PASTA-ELN/pasta-eln#107]
Steps to reproduce:
- Install the latest version of pasta APP (fresh installation of database also) Software version: trunk:latest
- Go through the "Repair setup tool" to populate the example project
- Try to add a projects/measurement/sample/procedures/instruments via GUI
- Go to Lists | Projects
- Click on "Add" button on the left top and see that the below given error is thrown
- ![Screenshot from 2023-10-26 12-36-39](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/758ae0bf-3f4e-4a60-9272-ebd4e4721337)
- ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/cfbd8622-99c3-4e5b-a59a-4fcd1f70a7ed)

Expected behavior:
- User should be able to add various items via application without any error

Tasks
- [ ] Fix for the problem: PR link:
- [ ] Verification complete :tada:

**Comment by HTsybenko** [comment]
Same error would occur when using "Group edit" of selected items.

**Comment by SteffenBrinckmann** [comment]
Pull request should repair both issues

**Comment by HTsybenko** [comment]
The issue was fixed.
