### ISSUE TITLE
Improve main form

### ISSUE THREAD

**Issue by SteffenBrinckmann** [PASTA-ELN/pasta-eln#11]
- make markdown correctly format immediately, right now user has to enter a ' ' or something
  - allow to move folder to different project
    Note: one can use unidentified for notes and move those
  - add vertical splitter to increase / decrease image
  - form: add button to add key-values
  - show all entries as non-edible things that can be copy-pasted
  - test how it looks with groups of questions and attachments

**Comment by HTsybenko** [comment]
Enhancements not implemented:
- make markdown correctly format immediately, right now user has to enter a ' ' or something
- allow to move folder to different project
Note: one can use unidentified for notes and move those

Enhancements implemented:
- add vertical splitter to increase / decrease image
- form: add button to add key-values

Unsure, what was meant under the enhancement suggestion: 
- show all entries as non-edible things that can be copy-pasted
- test how it looks with groups of questions and attachments

Please, create additional issues for the changes that still have to be implemented in the future.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko 
- For me the markdown is formated correctly immediately, I just verified it, for the comment. Can you give more details where it did not work for you and/or you show me on wednesday.
- "allow to move folder to different project" is a separate issue #192 
- "show all entries as non-edit": go to the form and there is a button next to save "Show all information", click it and you can now copy-paste everything
- I created a separate issue #226

**Comment by HTsybenko** [comment]
@SteffenBrinckmann 
1. For the markdown enhancement, you have written that "right now user has to enter a ' ' or something", which implies that this has to be changed. However, the editor still uses special symbols for changing styles, etc. If you meant something else, please specify it.
2. "show all entries as non-edit": it was not clear before, thanks for the explanation.
