### ISSUE TITLE
Long text in the project view header

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#110]
In the project view, if the project tags/objectives/status are very long and exceed the window width, the text goes over the window, and the blue project editing buttons disappear. 

Examples:

Long objective
![Screenshot from 2023-10-27 08-46-22](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/fe4f822a-66b9-4df1-95d3-50f4d98dd826)
Long tags
![Screenshot from 2023-10-27 08-48-30](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/58d39dc4-cf51-4da9-9d4c-39db24ff4e31)
Long status
![Screenshot from 2023-10-27 08-50-30](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/101abd30-a4d5-42b1-8c2e-ef497fcd67d3)

Also, the imported .eln files from other ELNs lead to the same issues.
For instance, import the [single-experiment.eln](https://github.com/TheELNConsortium/TheELNFileFormat/blob/master/examples/elabftw/single-experiment.eln) and check how the imported comment and content are shown in the project header.

The issue is the same as the closed #36, but it seems that the fix was not universal.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko I cannot reproduce for objective, I assume you have v2.4.20
For tags it was true and  I created a bugfix.

**Comment by HTsybenko** [comment]
The long project tags/objectives/status do not cause issues with the window size anymore.
