### ISSUE TITLE
Importing incorrect

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#115]
1) Export Pastas Example Project as an eln file. 
2) Execute the System – Configuration - Setup – Start analyze and repair command. No need to create the example project, it should remain empty. 
3) Then import the eln file. The message will appear to indicate a successful import. 
4) Go to Help-Verify database. 

Following messages will occur for multiple items:
      
dch15: critical error in x-2c8900a9643e43bfac977e18327c53c9
Traceback (most recent call last):
File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 901, in checkDB
parentDoc = self.getDoc(parentID)
File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 215, in getDoc
return dict(self.db[docID])
File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/database.py", line 706, in __getitem__
raise KeyError(key)
KeyError: 'x-6b908432e45f490a8556ae926ec2fd89'

dch16: shasum twice in view: 64175d01708672a4479cd5471b987f0008db8cbc m-dc4ccd5ebb3644b4b60e9cfe0d447597 simple.csv

Path of folder is non-unique: PastasExampleProject/002_DataFiles
disk(1) and db(2) content do not match:x-a0a266254b1d469ea774551d413009f8
values differ for key: _id
x-a0a266254b1d469ea774551d413009f8
x-5cdd701ba1354dd1be12432b2125bf7f
values differ for key: -date
2023-10-27T10:03:57.552794
2023-10-27T10:07:29.682389
branches differ
[{'stack': ['x-4d7b7a1a3668443c9d96b9adf556e6ff'], 'child': 2, 'path': 'PastasExampleProject/002_DataFiles'}]
[{'stack': ['x-6b908432e45f490a8556ae926ec2fd89'], 'child': 2, 'path': 'PastasExampleProject/002_DataFiles'}]
values differ for key: -user

**Comment by SteffenBrinckmann** [comment]
@HTsybenko I cannot reproduce this issue. 
From the error message, I have the feeling that the database integrity was not given when you did "1. Export Pastas Example Project as an eln file." Can you retry this, after a clean restart and see  if it happens again?
If it does happen again, we have to ask Jithu to help (set breakpoint at database.py", line 901 and look at the database)

**Comment by HTsybenko** [comment]
I have recorded three different scenarios, each resulting in different error messages during database verification (see  [Issue_115 folder on Sciebo](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu?path=%2FIssue_115)).

**Comment by HTsybenko** [comment]
For all three cases, the import issues have been solved.
