### ISSUE TITLE
Deleting structure levels 2 and 1

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#117]
The current version of Data Hierarchy Editor allows deleting the data types of structure levels 2 and 1 (Folders). 
When done so, the items of the corresponding data type would appear blank:

![Screenshot from 2023-10-27 10-47-17](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/a40bed0b-8e4a-48c6-b99c-f45d981fec18)

What should be the expected outcome for such a scenario? 
(For example: changing the items of the deleted structure level to another default structure level, 
keeping the original hierarchy for the existing projects and only altering it for the new ones, 
always keeping at least one structure level for folders?)

**Comment by HTsybenko** [comment]
Obviously, the deletion of these structure levels would also cause issues when using "Add child folder" and "Add sibling folder commands":
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/projectLeafRenderer.py", line 72, in paint
    docTypeText = self.comm.backend.db.ontology[doc['-type'][0]]['label'].lower()[:-1]
KeyError: 'x1'

**Comment by SteffenBrinckmann** [comment]
Fix the bugs; possibily create a new issue ..

**Comment by SteffenBrinckmann** [comment]
was easier than anticipated for the view
