### ISSUE TITLE
Export/import of items with the same name

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#126]
- Create a project in PASTA
- Go to any table view, for example- measurements
- Using "Add", create two measurement items in this project with the same name.
- Export the project as an eln file.
- Delete the project or execute the System – Configuration - Setup – Start analyze and repair command.
- Import the eln file. 
- Only one of the items with the same name will be imported.

Possible reason: During the creation of the eln file, it overwrites the item with the new one if the name is the same.

**Comment by SteffenBrinckmann** [comment]
We have to discuss that within the ELN consortium: uniqueness

**Comment by HTsybenko** [comment]
Both items with the same name are now exported to the eln file and imported from it as well.
