### ISSUE TITLE
Project header moved after changing Data Type

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#142]
- Go to any table view of a project.
 - Open any item to edit and change type to another Data type.
 - Click on the project title in the left side bar to open its project view.
 
The header will be moved to the center.
![Screenshot from 2023-11-17 15-29-27](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/da694f43-e123-4219-b6f0-a655fc99ba9d)

**Comment by SteffenBrinckmann** [comment]
Issue: old project view items not totally deleted before creating new, project header bar

**Comment by SteffenBrinckmann** [comment]
@HTsybenko While I also sometimes saw it happening, I cannot reliably reproduce it. Mostly this issue does not occur for me.
I added:
- a stop-gap measure to it: if at repainting the previous elements are not deleted, delete again.
- logging to report the number of elements in the project view: they should be 0->0->2->3 (this logging is on debug level, please change it to this to see if the issue still happens for you, starting in version 2.4.25

**Comment by HTsybenko** [comment]
Fixed, the project Header does not move as a result of the above-mentioned action sequence.
