### ISSUE TITLE
Importing items of other Data Types

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#143]
- Go to the Data Hierarchy editor.
- Create a new Data Type.
- Create a new project. 
- Go to the new Data Type table view and add an new item for it.
- Export the project as an eln file.
- Execute the System-Configuration-Setup-Start analyze and repair. 
- Import the eln file.

In the project view, the item of the new data type will be present. However, no table for this data type will be created, and the items that belong to this data type will not be added to the Unidentified category.

What would be a proper way to import such items?

**Comment by SteffenBrinckmann** [comment]
Abstract: "What happens to document with a non-zero data type, when you import it"?
Possible solutions; 
- unidentified -> non-measurement non-sample ....
- create data-type upon importing

**Comment by SteffenBrinckmann** [comment]
Decided to: 'unidentified" as users might want to delete datatype because of reasons. If pasta then recreates it, that  would make no sense. Hence, if datatype does not exist, it is unidentified. User can create a data type

**Comment by HTsybenko** [comment]
The  non-existing data types are moved to "unidentified" table.
