### ISSUE TITLE
Little side project: configAuthors.py

### ISSUE THREAD

**Issue by SteffenBrinckmann** [PASTA-ELN/pasta-eln#15]
- allow to add more users and each user can have multiple organizations

**Comment by HTsybenko** [comment]
How can I verify this enhancement?

**Comment by SteffenBrinckmann** [comment]
Use can add multiple organizations (see issue #222) 
If one cam and should be able to add multiple authors, that is a privacy question, to be addressed later

**Comment by SteffenBrinckmann** [comment]
To follow the privacy laws: reduce personal information. Close this feature request
