### ISSUE TITLE
Creating items in the project view

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#151]
The non-folder items can only be created in the table view of the corresponding Data Type category.

For convenience, the creation of items (samples, procedures, measurements, etc.) should also be allowed in the project view.

For instance, after right-clicking on an item in the project view, use an "Add other..." option in the appearing context menu, which would open another context menu with all available Data Types listed.

**Comment by HTsybenko** [comment]
In addition, "Rerun extractor" should also be given as an option during right click on the item in the project view.

**Comment by SteffenBrinckmann** [comment]
I am not sure about the "Rerun extractor" enhancement: re-running the extractor is not something that will be done often and for the sake of cleanliness / structure, I tend to be against that feature

**Comment by SteffenBrinckmann** [comment]
@HTsybenko There are enough issues in the pipe-line and we have not released a version for some time. I would suggest to not open new feature requests but only solve bugs. Hence I move this out of next version.

**Comment by SteffenBrinckmann** [comment]
Not sure how important these are. If users raise them in future, me issues will arise.
