### ISSUE TITLE
Auto-filling the "link" fields

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#152]
If an item has links to other items (samples, procedures, etc.), and this item is opened for editing, it will still show “-no link-” in the field of the corresponding link. This field should either be auto-filled with the saved option or be “-no change-” by default  (similarly to Project and Data type fields). 

Another suggestion is adding the “remove link” category to such lists. Otherwise, removing links between items is not possible.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko this is difficult: five measurements can link to the same sample, how would that be shown, edited, ... In the sample view?
I think it is better to have a: which item links to me? Search and display function, that would show for the sample that five measurements were done on it.
We have to discuss, I push issue out of next version, for now.

**Comment by HTsybenko** [comment]
@SteffenBrinckmann
- " five measurements can link to the same sample, how would that be shown, edited, ..."

Currently, we cannot view any links to measurements from the sample side, and the original issue also did not touch on this topic. We should discuss and create a separate issue for this.

- "I think it is better to have a: which item links to me? Search and display function, that would show for the sample that five measurements were done on it."

This point also sounds like an additional feature, and we should look at it separately from the issue mentioned here.


The problem I wanted to discuss is the following:
When one opens a measurement item with existing links to the sample or procedure, the sample and procedure fields show "no link", even if the link exists. Also, removing an existing link is not possible; one can only change it to a different one.

Here is one way I think we could treat this:
When opened to edit, a measurement has the linked sample pre-selected in the sample field. If no links were created previously, then "-no link-" as it is now by default. The "-no link-" could also allow the deletion of existing links if selected during editing. If multiple items with the same link were selected for group editing, the sample field would have a single value pre-selected. If multiple items with different links were selected for group editing, the sample field could show them as "multiple links."

A bit primitive but still more intuitive way: 
 A sample/procedure field in the measurement item editor shows "-link exists-" if a link was previously assigned and "-no link-" if no links were previously created. "-no link" also allows the link to be removed.
