### ISSUE TITLE
"Mark item as hidden" after "Hide item details"

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#166]
1) Open a project view
2) Right click on any item and select "Hide item details"
3) Right click on the same item and select "Mark item as hidden"

Error message:
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 131, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/projectTreeView.py", line 124, in execute
    self.comm.backend.db.hideShow(hierStack)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 648, in hideShow
    if doc['-type'][0][0]=='x':
UnboundLocalError: local variable 'doc' referenced before assignment

Log:
12-15 14:31:13|INFO:Start PASTA GUI
12-15 14:31:13|INFO:End PASTA GUI
12-15 14:31:14|DEBUG:project:changeProject |x-bc59c5f808fa46c98c6da68a6cc3070a||
12-15 14:31:14|DEBUG:ProjectView elements at 1: 0
12-15 14:31:14|DEBUG:ProjectView elements at 2: 0
12-15 14:31:14|DEBUG:ProjectView elements at 3: 2
12-15 14:31:14|DEBUG:ProjectView elements at 4: 3
12-15 14:31:20|DEBUG:Change project: docID s-ad4b486db2694728b893feb4f37136bb branch 0 | old stack ['x-bc59c5f808fa46c98c6da68a6cc3070a'] child 9999 | new stack ['x-bc59c5f808fa46c98c6da68a6cc3070a'] child 4 path None
12-15 14:31:20|DEBUG:success BRANCH updated with type and branch s-ad4b486db2694728b893feb4f37136bb sample  |  [{'stack': ['x-bc59c5f808fa46c98c6da68a6cc3070a'], 'child': 4, 'path': None, 'show': [True, True]}]

12-15 14:31:23|DEBUG:hide stack ['x-bc59c5f808fa46c98c6da68a6cc3070a', 's-ad4b486db2694728b893feb4f37136bb -']
12-15 14:31:23|DEBUG:  database list ['x-bc59c5f808fa46c98c6da68a6cc3070a', 's-ad4b486db2694728b893feb4f37136bb -'] 1

**Comment by SteffenBrinckmann** [comment]
Does not occur in the version 2.5 as many changes were made.

**Comment by HTsybenko** [comment]
The issue is fixed in 2.5.0b5.
