### ISSUE TITLE
Adding "Curated" column to the Project table view

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#171]
1) In the Project table view, go to "More-Change columns"
2) Select curated and move to the right field. Save.

The following error occurs:
**ERROR tableHeader menu unknown: [<Command.USE_TEXT: 5>]

**Comment by SteffenBrinckmann** [comment]
Seem to be fixed, as I debugged some things around this. 
- This will be checked, once version 2.5 is alive and then hopefully closed.

**Comment by HTsybenko** [comment]
The issue is fixed in 2.5.0b5.
