### ISSUE TITLE
Adding a new type leads to PASTA app crash

### ISSUE THREAD

**Issue by jmurugan-fzj** [PASTA-ELN/pasta-eln#176]
- Create a new type in data hierarchy editor
- ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/ac162f0b-914c-44a1-b72d-ba3214b12c2b)
- ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/5b8c1723-0ac4-4313-b0a4-cd0ae972f02d)
- Click save button and re-open the PASTA application to see the error below
![Screenshot from 2023-12-19 17-19-23](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/69a02276-1b29-410a-9b9e-64bac9e46355)

Expected behavior:
- Adding new type should not lead to main GUI crash

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Do you know what must be the reason for this error? Is "shortcut" a mandatory metadata for a type?

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj Yes, each data-type should have a "shortcut" and an "icon" key. If the user does not set it, the default is "". Can you do that?
Also, can you add a validator to the "create a new data type" to the datatype regex"^[a-wyz][a-z0-9_]+$"

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Please see the last comment in #106 I did not understand this requirement fully, please backlog with the requirements for the icon, shortcut etc as a feature, how you need it in UI and so on, once it's clear, I can start working on it!!

Regarding the regex, did you mean to defined regex for the "Datatype" field in  "create a new data type" dialog? it's already present, can you retry?

**Comment by HTsybenko** [comment]
In 2.5.0b5, adding a new data type and then saving does not throw errors anymore.
