### ISSUE TITLE
Installation of CouchDB via pastaELN Wizard not possible

### ISSUE THREAD

**Issue by moritzva** [PASTA-ELN/pasta-eln#182]
The installation of CouchDB via the pastaELN Wizard was not possible.

Trying to open pastaELN via `python -m pasta_eln.gui` resulted in:
>**ERROR dit01: Could not connect with username+password to local server 

Therefore, CouchDB installer was downloaded manually from the Website (apache-couchdb-3.3.3.msi).
During the installation of this file, username (admin) and password were set. Then, these steps were followed:

`(venv-pastaELN) (base) python -m pasta_eln.gui`

>**ERROR Configuration file does not exist or version is not 2

`(venv-pastaELN) (base) python -m pasta_eln.installationTools install`

>---- Create PASTA-ELN installation ----

>Enter user name:
>Enter password:

`(venv-pastaELN) (base) python -m pasta_eln.installationTools install`

>No errors

`(venv-pastaELN) (base) python -m pasta_eln.gui`

>Installation successful, access to CouchDB is possible.

**Setup**
 - OS: Windows 10
 - python 3.11.5 packaged by Anaconda
 - PASTA ELN Version: 2.1.4

**Comment by SteffenBrinckmann** [comment]
@moritzva Thank you for sending this first issue!

**Comment by SteffenBrinckmann** [comment]
Stash of information that was in the readme.md file but does not belong there anymore
### How to create a new version
1. Lint
1. Type checking: ignore extractors to keep them simple, some mistake might still remain
2. test documentation building. The documentation can be viewed with "firefox docs/build/html/index.html"
3. run test
4. ensure extractors updated
5. do normal commit
6. create a new version:
``` bash
pylint pasta_eln
mypy pasta_eln/*.py
make -C docs html
pytest -s Tests
diff -q ../Extractors/ pasta_eln/Extractors/ |grep differ

git commit -a -m 'linting and testing'

./commit.py "Minimal viable product" 1
```
   **THIS STEP IS NECESSARY FOR ALL GITHUB-Actions TO WORK**

### Create git-commit-hook
To automatically run many tests, create a file '.git/hooks/pre-commit' and make it executable
``` bash
#!/bin/sh
#
# Test if extractors updated
if [ "$(diff -q ../Extractors/ pasta_eln/Extractors/ |grep differ |grep extractor)" ]; then
  echo "Differences in EXTRACTOR EXIST"
  exit 1
else
  echo "All is correct: extractors match"
fi
# Run pylint
exec pylint pasta_eln
# Run mypy
exec mypy pasta_eln/*.py
# Test document creation
exec make -C docs html
# Run pytest
exec pytest -s tests
#
echo 'Pre-commit-tests are finished'
```
