### ISSUE TITLE
Closing the "You will loose all new data..." warning pop-up

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#224]
1. Open an item to edit.
2. Click cancel
3. Warning “You will loose all new data. Do you want to save it for next time?” appears.

If the user clicks on "X" in the top right corner, it will close both the warning and the editing window. 
The expected behavior would be to close the warning only with the editing window still being open.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko still an issue or closed after our discussion?

**Comment by HTsybenko** [comment]
The change was implemented.
