### ISSUE TITLE
Import of SampleDB.eln leads to segmentation fault

### ISSUE THREAD

**Issue by jmurugan-fzj** [PASTA-ELN/pasta-eln#231]
**Describe the bug**
Opening the imported measurements post import (of [sampledb_export.eln](https://github.com/TheELNConsortium/TheELNFileFormat/blob/bccc8e4b7c7adfde3b5f3b53b1207e755dc7f2fd/examples/SampleDB/sampledb_export.eln)) leads to seg core dump.

**Steps To Reproduce**
1. Run pasta-eln application
2. Click Project | Import menu to import [sampledb_export.eln](https://github.com/TheELNConsortium/TheELNFileFormat/blob/bccc8e4b7c7adfde3b5f3b53b1207e755dc7f2fd/examples/SampleDB/sampledb_export.eln) in pasta-eln. The import happens without any error.
3. ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/a27f3f75-9a3c-4450-aa11-441bf2b3fb78)
4. Click on project "Imported Project of SampleDB", select the measurement "schema.json" and click on the "json representation" as shown in the picture below.
5. ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/2f9516d2-e72a-49e1-b1fc-7b343519c1b6)
6. The above action leads to segmentation core dump
7. See the error below
8. ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/62bb4f23-676a-4a1e-a7c1-76a6a5bdeabf)
9. Once the error is thrown, the project shows no contents
10. ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/f200328a-0d4d-4a5b-8903-e35c7deea1fc)
11. ![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/bb702e08-f173-46db-8a9a-76a02f294af9)

**Expected behavior**
The experiment edit dialog should show up without any errors.

**Desktop (please complete the following information):**
 - OS: 22.04.1-Ubuntu
 - PASTA ELN Version: 2.5.0b6 (Latest main [checkout](https://github.com/PASTA-ELN/pasta-eln/commit/d235f405656e747d0f25d31a41a2100b9dde7e35) )

**Additional context**

**Comment by SteffenBrinckmann** [comment]
Does not occur in current version anymore
