### ISSUE TITLE
 “More-change columns” 

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#237]
- In a table view, go to “More-change columns”
- In the editing field (bottom left), add a new title for the column and move it to the right field.
- When saved, the respective column will appear in the table. 

- If the “More-change columns” table editor is opened again and the newly added column title is moved to the left field, it will be not saved in the list and will disappear. 

It would be therefore helpful if all added titles were stored in the left field when not selected for the display.
In addition, for the non-default titles, a remove button could be added.

**Comment by HTsybenko** [comment]
Also, in the "Help" pop-up window, it seems that the provided information is incomplete.

**Comment by SteffenBrinckmann** [comment]
Addressed by #337
