### ISSUE TITLE
Possible update for pyside6

### ISSUE THREAD

**Issue by srmnitc** [PASTA-ELN/pasta-eln#247]
The current version of [pyside6 in the requirements](https://github.com/PASTA-ELN/pasta-eln/blob/main/setup.cfg#L18) is outdated. Could this be updated? That would allow to go forward with the conda recipe https://github.com/conda-forge/staged-recipes/pull/25865

**Comment by SteffenBrinckmann** [comment]
We will address this requirement with the upcoming Ubuntu LTS update.

**Comment by SteffenBrinckmann** [comment]
Done
