### ISSUE TITLE
CouchDB not installed in pasta_eln-2.5.1b1

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#251]
1. When configuring a freshly installed PASTA-ELN version available by default (pasta_eln-2.4.27), there is an error during installation of CouchDB:
![Screenshot from 2024-04-05 11-35-19](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/7cb561ee-2bb8-4d8f-8405-689bf9524383)

2. If done manually via "sudo snap install couchdb", the installation is successful
couchdb 3.3.3 from Apache CouchDB installed

**Comment by SteffenBrinckmann** [comment]
@HTsybenko according to [1,2] this looks like a transient issue with the snap store (sometimes it works, sometimes not) and it has nothing to do with Pasta, can you try again, if it still persists.

[1] https://forum.snapcraft.io/t/error-http-status-code-408-snap-store/28980/4
[2] https://forum.snapcraft.io/t/503-response-codes-from-the-store-when-upgrading-the-chromium-deb-to-the-snap/16951

**Comment by HTsybenko** [comment]
It seemed to be quite persistent when I tried for the first time. Now it worked.
