### ISSUE TITLE
Details GUI issue

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#253]
1. Open a Measurement table
2. Open any item to edit
3. Add a link, save
4. In the right column, click on the link icon

The width of the fields will not be fitted and the fields extend over the right column width.

![Screenshot from 2024-04-08 09-24-51](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/0f67bc12-4b0a-4861-a818-b9fe527bb567)

**Comment by SteffenBrinckmann** [comment]
Measurements -> wiki image -> click on link (does not work)
