### ISSUE TITLE
Measurements in Unidentified table

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#264]
After installing or restoring the initial configuration, in the PASTAs example project, simple.png and simple.csv are found in the Unidentified table.

In addition, all new measurement files identified and processed by extractors during scanning appear in Unidentified.

Is this an expected behavior or a bug?

**Comment by SteffenBrinckmann** [comment]
@HTsybenko I found a reappearing bug in that context yesterday, extractors did not work correctly during rescan. Reason for reappearing bug: during rescan, the old type "unidentified" should be ignored. When the user purposefully sets 'unidentified' (last weeks bug), it should be considered as true. 
To answer your question: the example files should be working with the default extractors and identified as measurements, procedures, ...
I verify this later on, and also that the user choice "unidentified" is not ignored.

**Comment by HTsybenko** [comment]
The bug was fixed. The measurements now appear in the measurement table.
