### ISSUE TITLE
Complete uninstallation

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#267]
Currently, a user has to manually remove the PASTA-ELN and CouchDB related files and folders in order to uninstall the software.

This is an error-prone process and can lead to issues when reinstalling PASTA.
For instance, not removing a CouchDB folder (while the software itself is already uninstalled) leads to:

![Capture9](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/f15effd4-10ba-4f09-af7e-862f73a41a3a)

Ideally, the uninstallation sequence has to be automatized.

**Comment by SteffenBrinckmann** [comment]
It is not necessary anymore: everything can be uninstalled by pip; only data and config-json remains. data should remain.
