### ISSUE TITLE
Removing information from metadata fields

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#268]
Not all information from metadata fields can be deleted (by removing text in the editing field and saving). It was noticed for sample chemistry, procedure content, and instrument vendor.

The links to the samples and procedures cannot be removed, they can only be changed to different ones. Also, by default, the item editor shows “-no link-” in the fields where the links can be assigned. This was previously mentioned in #152 .

In addition, we can consider whether we need an option to unassign the project from the file. The corresponding item would then be moved to the “All (Measurements, etc.)” table, and the file itself could be moved from the project folder into the general PASTA working directory. This is also partially related to #153 .

**Comment by SteffenBrinckmann** [comment]
The last item in this list will be addressed in #192: moving between projects is addressed in that topic

**Comment by HTsybenko** [comment]
The metadata and links can be removed during individual item edits.
