### ISSUE TITLE
Changing the pasta application for the new version of ontology data

### ISSUE THREAD

**Issue by jmurugan-fzj** [PASTA-ELN/pasta-eln#28]
- Adapt the PASTA app for the latest version of ontology data set
- Find the latest version (pasta_eln/fixedStringsJson.py) committed as part of the branch feature/ontology_editor_fixed_string_update: PR [feat(ontology): added the new fixed string file #24](https://github.com/PASTA-ELN/pasta-eln/pull/24)
- Do the necessary modification to the app wherever it uses fixedStringsJson.py and also the loaded latest version of ontology data from CoucDB. The major change happened to the "prop" attribute and is converted to a dict of categories instead of list in the previous version
- Application should be able to handle both v2.0 and v3.0 (Is this needed for any scenarios?)
- Try to cover the changes as much as possible with unit & component tests

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann I have assigned this item to your name, please let me know if you could address this, or I can see this too, Thanks

**Comment by SteffenBrinckmann** [comment]
finished with #39
