### ISSUE TITLE
Importing eln file

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#295]
1) Create a project
2) Add some data and scan to add it to the project
3) Export the eln file of the project
4) System - Configuration - Setup - Start
5) Import the eln file

Process: ./test/Test/
Process: ./test/Test/000_ConfocalGwy/
Process: ./test/Test/000_ConfocalGwy/Al_10mN_5.gwy
Process: ./test/Test/000_ConfocalGwy/Al_10mN_2.gwy
Process: ./test/Test/000_ConfocalGwy/Al_80mN_2and5.gwy
Process: ./test/Test/000_ConfocalGwy/Al_160mN_2.gwy
Process: ./test/Test/000_ConfocalGwy/Al_40mN_3and4.gwy
Process: ./test/Test/000_ConfocalGwy/Al_80mN_1and6.gwy
Process: ./test/Test/000_ConfocalGwy/Al_10mN_1.gwy
Process: ./test/Test/000_ConfocalGwy/Al_160mN_5.gwy
Process: ./test/Test/000_ConfocalGwy/Al_10mN_3.gwy
Process: ./test/Test/000_ConfocalGwy/Al_160mN_3.gwy
Process: ./test/Test/000_ConfocalGwy/Al_10mN_6.gwy
Process: ./test/Test/000_ConfocalGwy/Al_40mN_2and5.gwy
Process: ./test/Test/000_ConfocalGwy/Al_40mN_1and6.gwy
Process: ./test/Test/000_ConfocalGwy/Al_10mN_4.gwy
Process: ./test/Test/000_ConfocalGwy/Al_80mN_3and4.gwy
Process: ./test/Test/000_ConfocalGwy/Al_160mN_6.gwy
Process: ./test/Test/000_ConfocalGwy/Al_160mN_1.gwy
Process: ./test/Test/000_ConfocalGwy/Al_160mN_4.gwy
Process: ./test/Test/000_ConfocalGwy/Al_20mN.gwy
Process: ./test/Test/001_IndentationHdf5/
Process: ./test/Test/001_IndentationHdf5/Al_20mN_load20s_hold5s.hdf5
Process: ./test/Test/001_IndentationHdf5/Al_10mN_load20s_hold5s.hdf5
Process: ./test/Test/001_IndentationHdf5/Al_160mN_load20s_hold5s.hdf5
Process: ./test/Test/001_IndentationHdf5/Al_80mN_load20s_hold5s.hdf5
Process: ./test/Test/001_IndentationHdf5/Al_40mN_load20s_hold5s.hdf5
Process: ./test/Test/Indentation procedure.md
Process: ./test/Test/Confocal Procedure.md
Process: ./test/data_hierarchy.json
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 127, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 159, in execute
    status = importELN(self.comm.backend, fileName)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/inputOutput.py", line 301, in importELN
    addedDocuments += processPart(part)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/inputOutput.py", line 256, in processPart
    backend.db.saveDoc(doc)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 247, in saveDoc
    doc['-client'] = tracebackString(False, 'save:'+doc['_id'])
KeyError: '_id'

The log and eln file are in the [Sciebo folder](https://fz-juelich.sciebo.de/s/UnH3XqsaNILMH4f)

**Comment by SteffenBrinckmann** [comment]
Does not occur in current version anymore
