### ISSUE TITLE
Ontology editor GUI changes

### ISSUE THREAD

**Issue by jmurugan-fzj** [PASTA-ELN/pasta-eln#30]
The following changes needs to be done for ontology editor UI:

1. Cancel button should cancel the whole operation and close the editor window
2.  Correct the default text for the type link line edit
3. Disable sorting icon in the table headers and also the first row
4. Adjust the column width for the properties table
5. Correct the radio button miss-alignment for the properties table
6. Keep same width for the Delete and Re-order button
7. Also for the attachment table, location column header is clipped, keep same width for delete and re-order buttons
8. At the moment, "xn" can be manually entered as a generic type and created. Attach validator to the titleLineEdit to not to allow titles with 'x' as first character or white-space when a new type is added
9. Populate the type checkbox rightly, structural items should be mapped to human readable names "Structure Level 0", "Structure Level 1",. .."Structure Level n"
10. Remove load button from the editor and simply loads all the data directly inside init method of editor

- Addressing comments from @SteffenBrinckmann as part of the previous PR: [feat(ontology): first draft version of ontology editor #8](https://github.com/PASTA-ELN/pasta-eln/pull/8)

1. Correct version number to 3 for ontology document
2. Correct the type for "required" property to boolean true/false in ontology document
3. Rearrange the columns of property table to  "name", "query", "list", "unit", "IRI", "required", "delete", "re-order"
4. Adjust the width of the columns of property & attachment table to reasonable size, with "query" column being widest
5. Change all "link" keys to "IRI" in ontology
6. Change the columns of attachment table to "Description" & "Type"

**Comment by SteffenBrinckmann** [comment]
Hey, can you also include a check that within each docType, the keys have to be unique
e.g. Sample can have "-name" only in one group and inside that group only once.

also: '-name', '-tags' have to exist within each docType e.g. docType=sample

**Comment by jmurugan-fzj** [comment]
For the help button functionality a separate bug has been created : "Add help button functionality to ontology editor tool #47"

**Comment by jmurugan-fzj** [comment]
For the scaling problem a different issue been created: _Auto-scale the whole UI elements when resizing the ontology editor window #48_

**Comment by jmurugan-fzj** [comment]
Since all the changes have been merged, hence closing this issue
