### ISSUE TITLE
Errors during corrosion data import

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#302]
After executing the "python -m pasta_eln.serverActions", a following error occurs:

**ERROR Could not get credentials from keyring 1. Please create manually.
import keyring as cred
myString = url+':'+adminUserName+':'+adminPassword
 url without http and port
cred.set_password('pastaDB','admin',myString)

The "import keyring as cred" also cannot be executed:
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421

**Comment by SteffenBrinckmann** [comment]
@HTsybenko it does not seem to be a bug of pasta, but one library changed or something similar. Can you open a normal python prompt and enter the import command " import keyring..." And see what happens.

**Comment by SteffenBrinckmann** [comment]
Not of relevance anymore: zip files are no longer supported
