### ISSUE TITLE
Qt plugin issue after new installation

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#308]
1. Python updated to 3.12.4, Ubuntu version 24.04
2. New environment was created for Python 3.12 to install PASTA-ELN
3. Regular installation via "pip install pasta-eln"
4. Started the application via "python3.12 -m pasta_eln.gui"

At this point, a following error occurs:

qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: wayland-egl, minimalegl, xcb, vkkhrdisplay, linuxfb, wayland, offscreen, vnc, minimal, eglfs.
Aborted (core dumped)

**The issue then is fixed by sudo apt-get install -y libxcb-cursor-dev.**

Should there be any changes to prevent this issue for the new installations?

**Comment by SteffenBrinckmann** [comment]
@HTsybenko can you specify pasta version?

**Comment by HTsybenko** [comment]
@SteffenBrinckmann In fact, the problem was encountered in both 2.6.0b1 and 2.3.6.

**Comment by SteffenBrinckmann** [comment]
fix is part of 2.6.0b2
