### ISSUE TITLE
CouchDB configuration in pasta_eln 2.3.6

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#309]
1. Python updated to 3.12.4, Ubuntu version 24.04
2. New environment was created for Python 3.12 to install PASTA-ELN
3. Regular installation via "pip install pasta-eln"

CouchDB installation window shows the following error:
![image](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/07a94137-bd71-4cd4-9959-d46eef94299b)

After that, repairing configuration and creation of an example project is also not possible:
**ERROR dit01: Could not connect with username+password to local server
*** CREATE EXAMPLE PROJECT AND SHOW ***
**ERROR: database.py:saveDoc could not save, likely JSON issue
{'-name': 'PASTAs Example Project', 'objective': 'Test if everything is working as intended.', 'status': 'active', 'comment': '#tag Can be used as reference or deleted', '-user': 'htsybenko', '-type': ['x0'], '-branch': [{'stack': [], 'child': 0, 'path': 'PastasExampleProject', 'show': [True]}], '_id': 'x-ddb5eff4277f490497855a0903e65b41', '-date': '2024-07-03T16:22:59.977815', '-tags': ['tag'], '-client': "main()|window = MainWindow()|sidebar = Sidebar(self.comm)  #sidebar with buttons|configWindow.exec()|exampleData(False, self.callbackProgress)|backend.addData('x0', {'-name': 'PASTAs Example Project', 'objective': 'Test if everything is working as intended.', 'status': 'active', 'comment': '#tag Can be used as reference or deleted'})|doc = self.db.saveDoc(doc)|tracebackString = traceback.format_stack()"}
Traceback (most recent call last):
  File "/home/htsybenko/pasta-env/lib/python3.12/site-packages/pasta_eln/dialogConfigSetupLinux.py", line 131, in analyse
    exampleData(False, self.callbackProgress)
  File "/home/htsybenko/pasta-env/lib/python3.12/site-packages/pasta_eln/installationTools.py", line 386, in exampleData
    backend.addData('x0', {'-name': 'PASTAs Example Project', 'objective': 'Test if everything is working as intended.', 'status': 'active', 'comment': '#tag Can be used as reference or deleted'})
  File "/home/htsybenko/pasta-env/lib/python3.12/site-packages/pasta_eln/backend.py", line 243, in addData
    if self.cwd is not None and doc['-type'][0][0]=='x':
                                ~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable


In contrast, pasta_eln-2.6.0b1 does not cause such issues:

![image](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/1739d7bf-1527-422d-8582-d624eb4172ac)

**Comment by SteffenBrinckmann** [comment]
Couchdb was not correctly installed, as such nothing can work. @HTsybenko
-  the conclusion is, 2.3.6 does not work with environments and new Ubuntu?
- we will tell people to encounter this problem to install the latest version, that should solve the issue, correct?

**Comment by SteffenBrinckmann** [comment]
At self, cause exception if cannot connect to server, pasta should stop immediate

**Comment by HTsybenko** [comment]
> Couchdb was not correctly installed, as such nothing can work. @HTsybenko
> 
> * the conclusion is, 2.3.6 does not work with environments and new Ubuntu?

My understanding is that the Ubuntu version has nothing to do with this since 2.3.6 worked well with 24.04 before the Python upgrade. The only difference was that it was previously tested in the Python 3.10.12 environment and the last time in 3.12.4.

> * we will tell people to encounter this problem to install the latest version, that should solve the issue, correct?

In my opinion, we should ensure that the officially released versions are stable for the most commonly used Python versions and test the basic functionality with those. From the user's perspective, enforcing a specific Python version for one particular package would not be welcomed.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko I don't, and never disagreed, with your last statement of the comment. I do see a point in stating obvious things and thereby suggesting that someone does have a different point of view.
Something strange has happened: 2.3.6b1 was there for a long time and no problems were reported; I explicitly asked about that a few days ago. And now, suddenly an issue is there with the full version, strange.
The only explanation I can see is that b1 was successfully tested without environment, as far as I understand your testing routine and the full version was unsuccessfully tested with environment.
- Can you please rerun your test with 2.3.6b1 and 2.3.6 with the environment?
- The other issue with 2.3.6 is likely connected to using a environment.

**Comment by HTsybenko** [comment]
> @HTsybenko I don't, and never disagreed, with your last statement of the comment. I do see a point in stating obvious things and thereby suggesting that someone does have a different point of view.

@SteffenBrinckmann I am sorry if I misinterpreted some of your previous comments.

> Something strange has happened: 2.3.6b1 was there for a long time and no problems were reported; I explicitly asked about that a few days ago. And now, suddenly an issue is there with the full version, strange. The only explanation I can see is that b1 was successfully tested without environment, as far as I understand your testing routine and the full version was unsuccessfully tested with environment.
> 
All the pasta_eln versions are always tested inside a venv. Previously, only Python 3.10.12 environments were used for the testing purposes.
After receiving a request on 02.07 to test the implementation of the PR [#284](https://github.com/PASTA-ELN/pasta-eln/pull/284), a new environment in 3.12.4 was created, and the discovered issues were then reported.

>     * Can you please rerun your test with 2.3.6b1 and 2.3.6 with the environment?
> 
>     * The other issue with 2.3.6 is likely connected to using a environment.

Here is a report of all tests executed today.

### Python 3.10.12

1. Default “pip install pasta_eln” installs **pasta_eln-2.5.3**
2. Installation also possible for 2.5.3b1 when the version is specified
3. 2.6.0b1 is not available, due to: ERROR: Ignored the following versions that require a different python version: 2.6.0b1 Requires-Python >=3.11

**Installation**: both pasta_eln-2.5.3, 2.5.3b1 installed without an issue.

**Starting** 2.5.3, 2.5.3b1: 

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File &quot;/usr/lib/python3.10/runpy.py&quot;, line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File &quot;/usr/lib/python3.10/runpy.py&quot;, line 86, in _run_code
    exec(code, run_globals)
  File &quot;/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/gui.py&quot;, line 11, in &lt;module&gt;
    from PySide6.QtCore import Qt, Slot, QCoreApplication  # pylint: disable=no-name-in-module
  File &quot;/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/PySide6/__init__.py&quot;, line 111, in &lt;module&gt;
    _setupQtDirectories()
  File &quot;/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/PySide6/__init__.py&quot;, line 60, in _setupQtDirectories
    from shiboken6 import Shiboken
  File &quot;/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/shiboken6/__init__.py&quot;, line 25, in &lt;module&gt;
    from shiboken6.Shiboken import *

### Python 3.11.9

1. Default “pip install pasta_eln” installs **pasta_eln-2.3.7 (old version)**
2. pasta_eln-2.5.3, 2.5.3b1 not available for installation
3. 2.6.0b1 can be installed when the version is specified

**Installation**: both pasta_eln-2.3.7 and 2.6.0b1 cab be installed without an issue.

**Starting** 2.3.7 and 2.6.0b1:

 A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/htsybenko/pasta_3_11/lib/python3.11/site-packages/pasta_eln/gui.py", line 4, in <module>
    from PySide6.QtCore import Qt, Slot      # pylint: disable=no-name-in-module
  File "/home/htsybenko/pasta_3_11/lib/python3.11/site-packages/PySide6/__init__.py", line 124, in <module>
    _setupQtDirectories()
  File "/home/htsybenko/pasta_3_11/lib/python3.11/site-packages/PySide6/__init__.py", line 64, in _setupQtDirectories
    from shiboken6 import Shiboken
  File "/home/htsybenko/pasta_3_11/lib/python3.11/site-packages/shiboken6/__init__.py", line 27, in <module>
    from shiboken6.Shiboken import *

**Comment by SteffenBrinckmann** [comment]
@HTsybenko Thank you. To simplify things, we now only concentrate on 2.6.0b2 (just-released and possibly b3); if that is working, it becomes the most recent release and all is well. Can you please test it:
- with python 3.10, 3.11, 3.12
- You can shortly note down if the shiboken and numpy issue are reported, but since we are not working on that software, we cannot do anything about it. So no need to spend energy on it.
- what would be interesting, if you write down the pyside6 version that is used in each case, as it might explain the shiboken....
- Can you report for each python version: if it installs and if pasta runs successfully at first glance. Also report in each case what the bash window says (you can copy-paste the text) as that is important.

**Comment by HTsybenko** [comment]
@SteffenBrinckmann 
## 2.6.0b2  tests:

### Python 3.10

**2.6.0b2 cannot be installed**

ERROR: Ignored the following versions that require a different python version: 2.6.0b1 Requires-Python >=3.11; 2.6.0b2 Requires-Python >=3.11
ERROR: Could not find a version that satisfies the requirement pasta_eln==2.6.0b2 (from versions: 2.0.1, 2.0.2, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.15, 2.0.16, 2.0.17, 2.0.18, 2.0.19, 2.0.20, 2.0.21, 2.0.22, 2.0.23, 2.0.24, 2.0.25, 2.0.26, 2.0.27, 2.0.28, 2.0.29, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.2.16, 2.2.17, 2.2.18, 2.2.19, 2.2.20, 2.2.21, 2.2.22, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.3.11, 2.3.12, 2.3.13, 2.3.14, 2.3.15, 2.3.16, 2.3.17, 2.3.18, 2.3.19, 2.3.21, 2.3.22, 2.3.23, 2.3.24, 2.3.25, 2.3.26, 2.3.27, 2.3.28, 2.3.29, 2.3.30, 2.3.31, 2.3.32, 2.3.33, 2.3.34, 2.3.36, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.14, 2.4.16, 2.4.17, 2.4.18, 2.4.19, 2.4.20, 2.4.23, 2.4.24, 2.4.25, 2.4.26, 2.4.27, 2.4.28, 2.5.0b3, 2.5.0b4, 2.5.0b5, 2.5.0b6, 2.5.0b7, 2.5.0b8, 2.5.0, 2.5.1b1, 2.5.1, 2.5.2b1, 2.5.2b2, 2.5.2, 2.5.3b1, 2.5.3)
ERROR: No matching distribution found for pasta_eln==2.6.0b2


### Python 3.11

**2.6.0b2 installs successfully**

Successfully installed Jinja2-3.1.4 MarkupSafe-2.1.5 Pillow-10.4.0 PySide6-Addons-6.7.2 PySide6-Essentials-6.7.2 QtAwesome-1.3.1 SecretStorage-3.3.3 aiohttp-3.9.5 aiosignal-1.3.1 anytree-2.12.1 attrs-23.2.0 backports.tarfile-1.2.0 cairocffi-1.7.1 cairosvg-2.7.1 certifi-2024.7.4 cffi-1.16.0 charset-normalizer-3.3.2 cloudant-2.15.0 contourpy-1.2.1 cryptography-42.0.8 cssselect2-0.7.0 cycler-0.12.1 defusedxml-0.7.1 fonttools-4.53.1 frozenlist-1.4.1 idna-3.7 importlib-metadata-8.0.0 jaraco.classes-3.4.0 jaraco.context-5.3.0 jaraco.functools-4.0.1 jeepney-0.8.0 keyring-25.2.1 kiwisolver-1.4.5 matplotlib-3.9.1 more-itertools-10.3.0 multidict-6.0.5 numpy-2.0.0 packaging-24.1 pandas-2.2.2 pasta_eln-2.6.0b2 pycparser-2.22 pyparsing-3.1.2 pypng-0.20220715.0 pyside6-6.7.2 python-dateutil-2.9.0.post0 pytz-2024.1 qrcode-7.4.2 qt-material-2.14 qtpy-2.4.1 requests-2.32.3 shiboken6-6.7.2 six-1.16.0 tinycss2-1.3.0 typing-extensions-4.12.2 tzdata-2024.1 urllib3-2.2.2 webencodings-0.5.1 yarl-1.9.4 zipp-3.19.2

**CouchDB: no issues**
![Screenshot from 2024-07-12 11-15-03](https://github.com/user-attachments/assets/904f1e25-3139-467c-8a5c-c926c7c021e5)

**Intitial “start analyze and repair” – no issues**


### Python 3.12

**2.6.0b2 installs successfully**

Successfully installed Jinja2-3.1.4 MarkupSafe-2.1.5 Pillow-10.4.0 PySide6-Addons-6.7.2 PySide6-Essentials-6.7.2 QtAwesome-1.3.1 SecretStorage-3.3.3 aiohttp-3.9.5 aiosignal-1.3.1 anytree-2.12.1 attrs-23.2.0 cairocffi-1.7.1 cairosvg-2.7.1 certifi-2024.7.4 cffi-1.16.0 charset-normalizer-3.3.2 cloudant-2.15.0 contourpy-1.2.1 cryptography-42.0.8 cssselect2-0.7.0 cycler-0.12.1 defusedxml-0.7.1 fonttools-4.53.1 frozenlist-1.4.1 idna-3.7 jaraco.classes-3.4.0 jaraco.context-5.3.0 jaraco.functools-4.0.1 jeepney-0.8.0 keyring-25.2.1 kiwisolver-1.4.5 matplotlib-3.9.1 more-itertools-10.3.0 multidict-6.0.5 numpy-2.0.0 packaging-24.1 pandas-2.2.2 pasta_eln-2.6.0b2 pycparser-2.22 pyparsing-3.1.2 pypng-0.20220715.0 pyside6-6.7.2 python-dateutil-2.9.0.post0 pytz-2024.1 qrcode-7.4.2 qt-material-2.14 qtpy-2.4.1 requests-2.32.3 shiboken6-6.7.2 six-1.16.0 tinycss2-1.3.0 typing-extensions-4.12.2 tzdata-2024.1 urllib3-2.2.2 webencodings-0.5.1 yarl-1.9.4

**CouchDB: no issues**

![Screenshot from 2024-07-12 11-19-12](https://github.com/user-attachments/assets/21e64381-809d-4eb8-832b-ea97049bc5c6)

**Intitial “start analyze and repair” – no issues**

**Comment by SteffenBrinckmann** [comment]
@HTsybenko Thank you, can you try again with 2.6.0b3?

**Comment by HTsybenko** [comment]
@SteffenBrinckmann The installation works for 2.6.0b3 in all three mentioned Python environments.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko can please check that the default installation is now 2.6.0 for all three python versions and that it starts correctly? Afterwards, close the related issues,  please.

**Comment by HTsybenko** [comment]
All three python environments install pasta_eln-2.6.0 by default.
