### ISSUE TITLE
Verify database before and after Dataverse upload

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#312]
- Python 3.12.4, Ubuntu 24.04, pasta-eln 2.6.0b in venv
 1. Go to Help-Verify database. When no projects were uploaded, the response would be:
DB verification:  dch01: branch does not exist -dataverseConfig-

2. Upload an item to Dataverse and then Help-Verify database again. The report would become:
DB verification:  dch01: branch does not exist -dataverseConfig-
dch01: branch does not exist b9d4b292448f0690d5b5bdb8c700bb62

Is there an issue related to these messages or should they be ignored?

**Comment by SteffenBrinckmann** [comment]
Clearly a bug in verify because it was created long time ago and could not now of the dataverse. Can be fixed.

**Comment by SteffenBrinckmann** [comment]
should be fixed in 2.6.0 or 2.6.0b3

**Comment by HTsybenko** [comment]
Fixed in 2.6.0.
