### ISSUE TITLE
Dataverse metadata autoselected

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#314]
- Python 3.12.4, Ubuntu 24.04, pasta-eln 2.6.0b in venv

When browsing through the Dataverse metadata editor, selecting some metadata definitions would also automatically pre-select their values, if there is a list to select from (see examples below).

This way, they would also appear in the metadata summary, and also will be automatically added to the uploaded dataset.

Most of the time, however,  all these metadata definitions are not needed for the upload. 
The user then has to delete them manually by clicking the "Delete" button on the right from the editing field, which is rather time-consuming. In addition, some metadata cannot be removed at all, since the Delete button is not active, e.g., Date of Deposit and Distribution Date in Citation metadata.

I suggest that upon selecting the metadata definition, no value for it should be pre-selected in the list.

![Screenshot from 2024-07-08 13-43-54](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/263492c5-00d0-461a-9006-7c667e2efe1e)
![Screenshot from 2024-07-08 13-42-48](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/cc7ec71a-e237-4364-badf-d11477d98439)
![Screenshot from 2024-07-08 13-42-38](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/07b593fc-e3c8-4c76-89a8-aca9114f6476)
![Screenshot from 2024-07-08 13-42-24](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/5ac46d85-c6a3-4ea5-8f6b-5cecd68e89df)
![Screenshot from 2024-07-08 13-42-08](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/f7a46544-39e7-4760-8447-0dae8c747da4)
![Screenshot from 2024-07-08 13-41-59](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/c927a1f8-3ac5-4f64-9d3b-ac06231dbcf8)
![Screenshot from 2024-07-08 13-41-50](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/b968d3d9-0422-479c-bfde-8bc8ac051b17)
![Screenshot from 2024-07-08 13-41-43](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/e11bf9b7-eb38-427e-8cfe-e95121895bdc)
![Screenshot from 2024-07-08 13-41-35](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/9b3960cd-dd2f-4f68-bed3-e1442fe23ea9)
![Screenshot from 2024-07-08 13-41-01](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/f1618450-1d95-4c4f-b6b2-de3b50982cea)
![Screenshot from 2024-07-08 13-40-43](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/6654451f-b654-4ab3-9d7f-5a6ac0bc207d)
![Screenshot from 2024-07-08 13-39-58](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/fcd4b50b-50af-442b-9bd2-46a30e9ef42b)
![Screenshot from 2024-07-08 13-38-58](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/d490813d-7089-45eb-bbd9-517b41dd0e8f)
![Screenshot from 2024-07-08 13-38-50](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/888cc660-90d0-4c5a-a4ac-986def3a2c9f)
![Screenshot from 2024-07-08 13-38-41](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/9af50532-85d8-4279-b1d4-f84979883abc)
![Screenshot from 2024-07-08 13-38-29](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/949e71ab-cba5-4a81-8ba1-8003253144cc)
![Screenshot from 2024-07-08 13-38-15](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/4ce11aa3-0196-4ea2-b9b4-e382ceea3529)
![Screenshot from 2024-07-08 13-37-55](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/4739d4e7-2876-45f5-955d-7e8c3b76baa8)

**Comment by jmurugan-fzj** [comment]
@HTsybenko This happens only when the used select that particular item from the list right? By default whenever a combo-list is displayed to the user once when he selects it, the first item is selected by default. Hence the behavior you seen in the application. Do you suggest to keep an empty item as the first one in the list always if nothing set before already? For every required primary fields, the delete button is disabled hence the case for "Date of Deposit", but need to see if the QDateEdit allows to clear the value or not!

For the second part, that's the behavior presently that all the edits across the "minimal" and "full" are preserved before the save click, do you want it differently? So you mean to reset all the edits between the "minimal" & "full" switches? So the behavior should be like the following?
- User done some edits on "minimal" items and now user switches to "full", then user do some "full" edits. When user clicks on "Save" button, the edits from "full" edits should be only persisted?
- Similarly the other way, User done some edits on "full" items and now user switches to "minimal", then user do some "minimal" edits. When user clicks on "Save" button, the edits from "minimal" edits should be only persisted?

Is this the behavior expected? In my opinion, I would assume to preserve all the edits between minimal and full, because minimal is only a way of displaying the required fields from the full list! Just an easy way to set the needed items while doing the edits! Let me know your opinion..

**Comment by HTsybenko** [comment]
> @HTsybenko This happens only when the used select that particular item from the list right? By default whenever a combo-list is displayed to the user once when he selects it, the first item is selected by default. Hence the behavior you seen in the application. Do you suggest to keep an empty item as the first one in the list always if nothing set before already? For every required primary fields, the delete button is disabled hence the case for "Date of Deposit", but need to see if the QDateEdit allows to clear the value or not!

@jmurugan-fzj Exactly, when the metadata category, such as Language, is selected, the first item "Abkhaz" will be selected there automatically. An empty item would definitely make more sense. For the required fields, one receives a message anyway, if those are not filled,  so an empty item would work there as well.

> 
> For the second part, that's the behavior presently that all the edits across the "minimal" and "full" are preserved before the save click, do you want it differently? So you mean to reset all the edits between the "minimal" & "full" switches? So the behavior should be like the following?
> 
> * User done some edits on "minimal" items and now user switches to "full", then user do some "full" edits. When user clicks on "Save" button, the edits from "full" edits should be only persisted?
> * Similarly the other way, User done some edits on "full" items and now user switches to "minimal", then user do some "minimal" edits. When user clicks on "Save" button, the edits from "minimal" edits should be only persisted?
> 
> Is this the behavior expected? In my opinion, I would assume to preserve all the edits between minimal and full, because minimal is only a way of displaying the required fields from the full list! Just an easy way to set the needed items while doing the edits! Let me know your opinion..

Here, I would expect that by selecting "minimal" or "full", the user decides which set of metadata has to be posted.
In principle, the edits across "minimal" and "full" should be preserved, but if in the editing window, the "minimal" is selected in the top field, then upon clicking "save", only the terms from "minimal" should be used for the upload.

**Comment by jmurugan-fzj** [comment]
@HTsybenko But when you successfully save something the whole editor will be closed, then the user will not get a chance to save the modified edits in the other list!! So you want to change this behavior also that the "Save" click should not close the editor and to only allow the user to close the editor when the user clicks "close" or "cancel" button?

**Comment by HTsybenko** [comment]
@jmurugan-fzj I'm Not sure I fully understand this problem.
Currently, I can open the metadata editor, edit fields, then click "save".
After saving, "Metadata Summary" appears, which shows all the metadata that will be posted during upload.
Afterwards, I click "Yes", which closes the editor. Then, I select the projects and start my upload.

Later on, when I opened the metadata editor again, all the fields that were edited before (both in Full and Minimal) contained that previously edited metadata, which was expected.

So the "Save" would still save all the edited fields as before, but the "Full" or "Minimal" should decide what fields appear in the "Metadata Summary" and will be posted during upload.

**Comment by jmurugan-fzj** [comment]
@HTsybenko See the following steps:
- User selects "minimal", done some edits
- Switches to "full", done some edits
- Click save button, the changes from full will be summarized. 
- User clicks "Yes" button and the only summarized changes from "full" will be saved and the editor will be closed!

_So the user does not get a chance to summarize and save the edits in the "minimal" list, don't you see this as a problem?_

**Comment by HTsybenko** [comment]
We agreed to change the displayed presets in the top field of the metadata editor to "Display full" and "Display minimal" and discuss remaining issues later.
