### ISSUE TITLE
Cansellation of Dataverse upload

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#315]
- Python 3.12.4, Ubuntu 24.04, pasta-eln 2.6.0b in venv

In the case that project upload is cancelled, the dataset instance on Dataverse is still created, but is empty.  

Is it possible to automatically remove such an empty dataset from the repository when cancelling the upload?

**Comment by jmurugan-fzj** [comment]
@HTsybenko No deletion of data is not possible, if you pass the creation step, this will be persisted and data-verse does not support deletion except for the administrators!
