### ISSUE TITLE
Right click in project view

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#319]
- Pasta version 2.6.0.b2, Python 3.11

1) Open any project in a project view
2) Right click on any item or empty area

Traceback (most recent call last):
  File "/home/htsybenko/pasta_3_11/lib/python3.11/site-packages/pasta_eln/GUI/projectTreeView.py", line 55, in contextMenuEvent
    context.exec(p.globalPosition().toPoint())
                 ^^^^^^^^^^^^^^^^
AttributeError: 'PySide6.QtGui.QContextMenuEvent' object has no attribute 'globalPosition'

Expected behavior: No error messages, right click opens a context menu with options.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko can you also specify the pyside6 version? Can you try with python 3.12, too?

**Comment by HTsybenko** [comment]
@SteffenBrinckmann Same with python 3.12, both have pyside6-6.7.2.
