### ISSUE TITLE
Button should highlight premature end of install

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#32]
Following issues were discovered when trying to repair configuration via System – Configuration - Setup – Start analyze and repair:
- During repairing, the progress bar overlaps with “finished button” and the above text field.
- After repairing, the “finished” button triggers the repairing process again instead of closing the window.
- After repairing, the removed projects still appear in the left side bar and can be opened from there (appear empty). Restarting Pasta GUI removes them from the left side bar.

**Comment by SteffenBrinckmann** [comment]
I cannot test / debug this on my system since that has data. I will try to find alternative.

**Comment by HTsybenko** [comment]
The bugs mentioned in the original post were fixed in the newest version.

However, another small issue was discovered:
System – Configuration- Setup – Start analyze and repair
When the new window “Do you want to create an example project” pops up, press the “Enter” button, and the window will disappear.
The bottom button in the "Start analyze and repair" window will now change to “Finished”, even though the resetting of configuration did not actually happen.

**Comment by SteffenBrinckmann** [comment]
This behavior is as expected: there is a number of tasks that are executed after each other. Even if one step is not-done/fails/etc, after that the list of tasks is 'finished'

**Comment by HTsybenko** [comment]
It was not intuitive enough for me then because it seemed like a bug. I would consider the list "finished" when all steps were completed.

**Comment by SteffenBrinckmann** [comment]
Lets discuss this question of nomenclature at next meeting.

**Comment by SteffenBrinckmann** [comment]
Change button label "Finished without creating example project"
