### ISSUE TITLE
Moving files inside and outside the GUI

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#322]
- Pasta version 2.6.0.b2, Python 3.11

Previously, it was possible to drag-and-drop the items from one folder to another within PASTA project view.
This type of action would also move the corresponding items in the PASTA working directory in the same manner.

Currently, this feature is not available anymore and files are not moved outside the GUI. 
Is this an intended behavior?

**Comment by SteffenBrinckmann** [comment]
@HTsybenko, BUG! Any error message in the terminal or the log-file?

**Comment by HTsybenko** [comment]
@SteffenBrinckmann Nothing in the terminal.

Log:

07-12 16:05:23|DEBUG:project:changeProject |x-c6e005f4ced147dfbc1dfc7e188cbd9c||
07-12 16:05:23|DEBUG:ProjectView elements at 1: 0
07-12 16:05:23|DEBUG:ProjectView elements at 2: 0
07-12 16:05:23|DEBUG:ProjectView elements at 4: 3
07-12 16:05:31|DEBUG:Change project: docID m-a2e97871ef2643ecb7e8713ddcebd58d branch 0 | old stack ['x-c6e005f4ced147dfbc1dfc7e188cbd9c', 'x-353c9620fb4e46508f4e60be3267e55c'] child 9999 | new stack ['x-c6e005f4ced147dfbc1dfc7e188cbd9c', 'x-3f4d75737502478e93113d4debf91a4a'] child 0 path PastasExampleProject/002_DataFiles/simple.csv
07-12 16:05:31|DEBUG:success BRANCH updated with type and branch m-a2e97871ef2643ecb7e8713ddcebd58d measurement/csv  |  [{'stack': ['x-c6e005f4ced147dfbc1dfc7e188cbd9c', 'x-3f4d75737502478e93113d4debf91a4a'], 'child': 0, 'path': 'PastasExampleProject/002_DataFiles/simple.csv', 'show': [True, True, True]}]

07-12 16:05:31|DEBUG:Change project: docID m-a2e97871ef2643ecb7e8713ddcebd58d branch 0 | old stack ['x-c6e005f4ced147dfbc1dfc7e188cbd9c', 'x-3f4d75737502478e93113d4debf91a4a'] child 0 | new stack ['x-c6e005f4ced147dfbc1dfc7e188cbd9c', 'x-3f4d75737502478e93113d4debf91a4a'] child 0 path PastasExampleProject/002_DataFiles/simple.csv

**Comment by SteffenBrinckmann** [comment]
Note: branch is also not updated

**Comment by SteffenBrinckmann** [comment]
There was a change to the code (project.py:346) at git:23eca9b3919c092fe29d3b03af609d1149a9df28
-    if branchOld['path'] is not None and not branchOld['path'].startswith('http'):
+    if doc['-type'][0][0]=='x':
Which was connected to issue #269 
That fix was not good.
