### ISSUE TITLE
Changing project details (3.0)

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#334]
1. Add a new project. Add an objective and a status.
2. Open the project. The objective and the status will be shown as.

![Screenshot from 2024-09-06 14-33-16](https://github.com/user-attachments/assets/79180278-4ff5-4bfb-9fcc-a83b4db1ad50)

3. Edit the project:
**WARNING dialogForm: unknown value type. key:.status, type:<class 'str'>
**WARNING dialogForm: unknown value type. key:.objective, type:<class 'str'>

**Comment by SteffenBrinckmann** [comment]
Two issues remain:
- combobox choice saved in database not used as default option: make it always
- save of project after edit(3.) does not work as supposed

**Comment by SteffenBrinckmann** [comment]
Fixed
