### ISSUE TITLE
comment in project view

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#36]
In the project view, if the project comment is very long and exceeds the window width, the comment goes over the window and the blue project editing buttons disappear.

**Comment by SteffenBrinckmann** [comment]
yes, it is true and a know issue. When I tried to fix it, I did not find a solution

**Comment by SteffenBrinckmann** [comment]
same as issue #20

**Comment by SteffenBrinckmann** [comment]
repaired in #74

**Comment by HTsybenko** [comment]
After updating to the latest version (2.4.14), I can still reproduce the issue described in the original post.
[Sciebo video for Issue 36](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu#/files_mediaviewer/Issue_36_long%20comment%20in%20project%20view.webm)

**Comment by SteffenBrinckmann** [comment]
Yes, it is not there yet

**Comment by HTsybenko** [comment]
In 2.4.16, the issue is partially resolved. Lengthy project comments are displayed without extension over the GUI window, and do not affect the blue buttons on the top right.

However, when the comment exceeds certain length, an empty field occurs below it, as shown in the screenshot below.

![Screenshot from 2023-10-13 15-04-50](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/15de334a-16d5-4e63-80e8-81a1dd10c13a)

If needed, this can be reported as a separate issue.

**Comment by HTsybenko** [comment]
The original problem was fixed. Other issues related to the display of comments will be opened separately.
