### ISSUE TITLE
Import of own .eln files

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#38]
If a project was created in Pasta, then exported as an eln file, deleted via GUI and then its .eln file is imported, the data files are imported and the links between measurements and samples, etc., as well as comments are restored completely, as intended. 

If the project is exported as an .eln and then the configuration was repaired to default, then during the import of the .eln file, the data files are not imported into the DB (file on harddisk but not DB message occurs during verification). If scanned afterwards, the files are added to the project, but without links or comments

**Comment by SteffenBrinckmann** [comment]
the import of an exported .eln file does not work, if the following command is executed before: System – Configuration - Setup – Start analyze and repair.

If this is the case, there is no error message during the import of .eln file, but the data files do not appear in the project afterwards.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko I tried it again using the indentation demonstrator and it works for me. How can I understand what I do differently than you?

**Comment by HTsybenko** [comment]
@SteffenBrinckmann 

I have added two screencasts to the shared Sciebo folder to make it possible to reproduce this issue. 

The first one demonstrates adding and annotating data files to the new project, and shows how the finalized project looks like before exporting it as an .eln file. The second includes the steps that lead to the issues described above:  System – Configuration - Setup – Start analyze and repair, then import of the .eln file.

You can directly try importing the .eln file in the Sciebo folder to recreate the issue.

**Comment by SteffenBrinckmann** [comment]
Thank you. Looking at the log-file clarified the issue.
- _attachment cannot be recreated and fails.
- I will fix it

**Comment by SteffenBrinckmann** [comment]
Should be repaired by #60

**Comment by SteffenBrinckmann** [comment]
@HTsybenko can you check in the next version?

**Comment by HTsybenko** [comment]
The issue is partially resolved in the latest version, and generally, the re-import of own eln files, comments, and links into the newly repaired database works.
The remaining problems with importing own eln files will be reported in a new issue.
