### ISSUE TITLE
Issues when minimizing/maximizing individual items in projects

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#56]
In Example Pasta project, right click on the any item (ExampleSOP.md in this example) and select Minimize/Maximize.
The item details will hide as intended.
Then right click on the same item and Minimize/Maximize again.
On the place of the changed item, a new item for the PastasExampleProject occurs.

In the terminal, the following error occurs:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/project.py", line 243, in modelChanged
    db.updateBranch(docID=docID, branch=branchIdx, stack=stackNew, path=pathNew, child=childNew)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 431, in updateBranch
    (self.basePath/oldPath).rename(self.basePath/path)
  File "/usr/lib/python3.10/pathlib.py", line 1234, in rename
    self._accessor.rename(self, target)
OSError: [Errno 22] Invalid argument: '/home/htsybenko/Data/PastasExampleProject' -> '/home/htsybenko/Data/PastasExampleProject/PastasExampleProject'

Report of DB verification afterwards:

List all database entries
branch stack and path lengths not equal: m-0aeaff76e3f3454e81d043f23017d0e9 | https:/upload.wikimedia.org/wi
dch08: parent does not have corresponding path (remote content) p-c6d2a44f343849a99edadd9892081958 | parentID x-150b212c6a92454b9835468423f4be9d
dch08: parent does not have corresponding path (remote content) x-2b5152c28dc14601aa3877b5e9d58c88 | parentID x-150b212c6a92454b9835468423f4be9d
dch08: parent does not have corresponding path (remote content) x-8e826264c8e44bcaa5f2c37d4f4982fc | parentID x-150b212c6a92454b9835468423f4be9d
dch08: parent does not have corresponding path (remote content) x-b446316da7664e2193b456ba17d7c9af | parentID x-150b212c6a92454b9835468423f4be9d
dch08: parent does not have corresponding path (remote content) x-b8524dd02b444530b95abcf1eebb6e52 | parentID x-150b212c6a92454b9835468423f4be9d
dch08: parent does not have corresponding path (remote content) x-f71d9ec3844145c49b218974d1ed921e | parentID x-150b212c6a92454b9835468423f4be9d
List problematic database tables
File status
Number of files on disk that are not in database 0
bch01: These files of database not on filesystem:
- PastasExampleProject/PastasExampleProject

Log:
09-26 12:22:50|INFO:Start PASTA GUI
09-26 12:22:51|INFO:End PASTA GUI
09-26 12:23:04|DEBUG:project:changeProject |x-150b212c6a92454b9835468423f4be9d||
09-26 12:23:07|DEBUG:Change project: docID -old- -new- p-c6d2a44f343849a99edadd9892081958|['x-150b212c6a92454b9835468423f4be9d']  0|['x-150b212c6a92454b9835468423f4be9d'] 3 PastasExampleProject/003_Example_SOP.md
09-26 12:23:07|DEBUG:success BRANCH updated with type and branch p-c6d2a44f343849a99edadd9892081958 procedure/markdown  |  [{'stack': ['x-150b212c6a92454b9835468423f4be9d'], 'child': 3, 'path': 'PastasExampleProject/003_Example_SOP.md', 'show': [True, True]}]

09-26 12:23:18|DEBUG:Change project: docID -old- -new- x-150b212c6a92454b9835468423f4be9d|[]  0|['x-150b212c6a92454b9835468423f4be9d'] 3 PastasExampleProject/PastasExampleProject
09-26 12:23:18|DEBUG:Target folder's json does not exist: PastasExampleProject/PastasExampleProject
09-26 12:23:18|DEBUG:success BRANCH updated with type and branch x-150b212c6a92454b9835468423f4be9d x0  |  [{'stack': ['x-150b212c6a92454b9835468423f4be9d'], 'child': 3, 'path': 'PastasExampleProject/PastasExampleProject', 'show': [True, True]}]

**Comment by SteffenBrinckmann** [comment]
Yes, this was a known issue and should be fixed by the upcoming version 2.4.13. Please check if it still exists there.

**Comment by HTsybenko** [comment]
The bug is fixed in the latest version.
