### ISSUE TITLE
Deletion of an item in table view

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#57]
Open any table view and use “add” button to create an item.
Select this item by clicking on its checkbox.
Go to "selection" and click on “delete”.
The item will not be deleted, and the following error occurs in terminal:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 131, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/table.py", line 272, in execute
    oldPath = self.comm.backend.basePath/branch['path']
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

DB verification report:
dch10: shasum not in measurement m-f4589df59fd14971a67ad14f6ee60a8c
image not valid m-f4589df59fd14971a67ad14f6ee60a8c 

Log:
09-26 12:54:56|DEBUG:table:changeTable |measurement|x-60ec47c727674e11bed0861fd1ec815a|
09-26 12:54:58|DEBUG:gui:formdoc of type ['measurement']
09-26 12:55:07|DEBUG:Add/edit data in cwd:/home/htsybenko/Data with stack:['x-60ec47c727674e11bed0861fd1ec815a'] and name: Test item type:['measurement'] and edit: False
09-26 12:55:07|DEBUG:successfully saved doc with type and branch m-f4589df59fd14971a67ad14f6ee60a8c measurement  |  [{'stack': ['x-60ec47c727674e11bed0861fd1ec815a'], 'child': 9999, 'path': None, 'show': [True, True]}]

09-26 12:55:09|DEBUG:details:changeDetails |m-f4589df59fd14971a67ad14f6ee60a8c|

**Comment by SteffenBrinckmann** [comment]
@HTsybenko Very good bug report. Amazing, because I could see the bug from it directly.

**Comment by HTsybenko** [comment]
This issue is fixed now.
