### ISSUE TITLE
Auto-populating IRI field of ontology editor 

### ISSUE THREAD

**Issue by jmurugan-fzj** [PASTA-ELN/pasta-eln#58]
_A mechanism should be integrated to populate all the IRI fields in the GUI of ontology editor tool. User must be able to type in certain search terms and should populate "Internationalized Resource Identifier" found for the given terms_

![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/0abca3cf-eb11-44c5-b178-247f5d371444)

- The search term to be used for the lookup has to be the name "column" value in case of property table

Info:
- The branch ([Raphael](https://github.com/PASTA-ELN/pasta-eln/tree/Raphael)) created by @RaphaelRoeske has an implementation which retrieves the necessary data from various portals 
- This implementation needs to be merged and integrated with ontology editor tool

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann I have a query regarding the searchterm to be used for populating IRI at the datatype level, for e.g if you see the picture below, what should be search term to be used automatically in this case by the lookup tool?

![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/ee2dab1c-6704-4ade-ad5d-d2439f8ce9e6)

**Comment by SteffenBrinckmann** [comment]
It can only be projects, as there is no other words in that line that is user changeable
