### ISSUE TITLE
Improving user experience with "Visibility" options

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#62]
### Visibility options discussed one by one:

- In the project table view, visibility options appear under the “More” button, and the only option is “Display/omit hidden items”. When there is a hidden project, clicking on the “Display/omit hidden items” option makes it hidden or visible with an “eye” sign in the project table view. This change is permanent until undone.

- In the project view, the following visibility options are under “Visibility”: 
     - “Minimize/Maximize project details” only shows/hides project details. This change is not permanent and is undone when the project view is reopened.
     - “Display/omit hidden subitems” is supposed to hide or show the items marked as hidden. This change is permanent until undone. 
        - Not sure if this is intended, but this option affects both hidden items and project details. If the project details are hidden (minimized), and the hidden items are visible, clicking on “Omit hidden subitems” will not only hide the hidden item but also display the project details.  If both project details and hidden items are hidden, clicking “Display hidden subitems” will show the hidden items and project details.
    - “Hide entire project” hides the entire project and returns to the project list. This change is permanent until undone.
        - From the user's point of view, it would be clearer to understand what happened if when clicking “Hide entire project”, the project table view is shown with the hidden project marked with an “eye” symbol. first. From here, the user can use “Display/omit hidden items” to hide all projects marked as hidden.

    - “Minimize/Maximize subitems” hides item details in the project view. This change is not permanent and is undone when the project view is reopened. 
        - Might be a bug: If the items are minimized, and the project view is then reopened, the items are displayed as maximized again, which is intended. However, there is no change after “Minimize subitems” is clicked again to minimize the items. The “Minimize subitems” must be clicked twice to function in this case.
- In the (measurement, sample, etc.) table view, the visibility options appear under “Selection” and “More”. To hide items, one has to select an item by clicking its checkbox, go to “Selection,” and click “Toggle hidden”. To switch visibility, one has to go to the “More” button and select “Display/Omit hidden items”.

### General improvement suggestions:
- The placement of visibility options is not intuitive for the users. They can be found either under “More” in the project table view, under “Visibility” in the project view, or under “Selection” and “More” in other table views. A better way would be to have a single “Visibility” button for all table and project views. This button may have the “eye” symbol instead of the “Visibility” text to save space and make the options more intuitive.

- Make the not-permanent visibility options in the project view permanent. When the user uses “Minimize/Maximize project details” and “Minimize/Maximize subitems”, remember the specific project changes until the user undoes them manually. Thus, there would be no difference in using different visibility options, and all would be functioning more consistently.
- Many display options have different names but nearly the same functionality. Sometimes, the naming does not fully correspond to the functionality. To make the naming clear, all the options that make items or projects marked as hidden (with an eye) could be named as “Toggle hidden” or “Mark as hidden”, and all the other options then could be renamed to “Hide/show”. For Example:
    - In Project table view: “Display/omit hidden items” change to “Hide/show hidden projects”. 
    - In Project View:
        - “Minimize/Maximize project details” change to “Hide/show project details” 
        - “Display/Omit hidden subitems” change to “Hide/show hidden items”
        - “Hide/Show entire project” changes to “Mark project as hidden”
        - “Minimize/Maximize subitems” change to “Hide/show item details”
        - When right-clicking on the item in Project View, “Hide/show” change to “Mark item as hidden”.
    - Other table views: “Toggle hidden” change to “Mark selected as hidden” “Display/Omit hidden items” change to “ Hide/show hidden items”.

**Comment by HTsybenko** [comment]
This issue is meant for discussion. If we agree on specific changes, separate issues will be created for each.

**Comment by SteffenBrinckmann** [comment]
Can we also discuss: what should happen if the user clicks hide in project view: should the data be immediately hidden or remain visible (with eye-icon) and upon refresh disappear?

**Comment by SteffenBrinckmann** [comment]
I removed the "keep things permanent" items from this todo list. These changes will go into milestone 2.5. 
Permanent issues are too risky and might go into Version 2.6
