### ISSUE TITLE
Markdown editor  - heading styles

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#64]
Open any project/item to edit its details.
In the comment editor section, go to “More” to open Markdown editor.
Click on any heading style option (H1, H2 or H3) on the top of the editing field.
This raises an error:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 101, in <lambda>
    self.clicked.connect(lambda: widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 378, in execute
    getattr(self, f'textEdit_{command[2]}').insertPlainText('#' * int(command[-1]) +' Heading\n')
ValueError: invalid literal for int() with base 10: 'comment'

Log:
09-28 14:00:22|INFO:Start PASTA GUI
09-28 14:00:22|INFO:End PASTA GUI
09-28 14:00:24|DEBUG:project:changeProject |x-d92a27adbd1b4a68a23b211c1030de99||
09-28 14:00:26|DEBUG:gui:formdoc m-f26e9a9e4db24141bf2a048a13a0ee26

**Comment by SteffenBrinckmann** [comment]
repaired in #71

**Comment by HTsybenko** [comment]
I could still reproduce this issue in the newest version.

Error message:
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 101, in <lambda>
    self.clicked.connect(lambda: widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 378, in execute
    getattr(self, f'textEdit_{command[2]}').insertPlainText('#' * int(command[-1]) +' Heading\n')
ValueError: invalid literal for int() with base 10: 'comment'

Log:
10-05 19:49:34|INFO:Start PASTA GUI
10-05 19:49:35|INFO:End PASTA GUI
10-05 19:49:37|DEBUG:project:changeProject |x-ee30f8fca06540dda0e1886dd51064f8||
10-05 19:49:38|DEBUG:gui:formdoc p-0834b0789a57484192632dbd95030f3c
10-05 19:49:41|DEBUG:Change project: docID -old- -new- p-0834b0789a57484192632dbd95030f3c|['x-ee30f8fca06540dda0e1886dd51064f8']  0|['x-ee30f8fca06540dda0e1886dd51064f8'] 3 PastasExampleProject/003_Example_SOP.md

**Comment by SteffenBrinckmann** [comment]
Yes, it is not in the released version, yet.

**Comment by HTsybenko** [comment]
Clicking on heading styles does not raise an error anymore, therefore the issue is closed.
