### ISSUE TITLE
Cancel export eln

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#65]
Go to Project – Export .eln

When the new file explorer window opens, click cancel.
This will still trigger saving an .eln file, which is not an expected behavior. 
Moreover, it will overwrite an .eln file with the same name if such exists, without an active agreement from the user.

**Comment by SteffenBrinckmann** [comment]
Repaired in PullRequest #70

**Comment by HTsybenko** [comment]
The issue is still there after the upgrade.

**Comment by HTsybenko** [comment]
The issue is fixed now, cancelling the export works.
