### ISSUE TITLE
Importing .eln with unidentified->measurement files

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#79]
1) Create a project in PASTA and add some unidentified files to it.
2) Change the data type of the unidentified files to "measurements".
3) Go to Project-Export .eln and create an eln file from the project.
4) Execute the command: System – Configuration - Setup – Start analyze and repair
5) PASTA restarts
6) Go to Project-Import .eln and reimport the project from the eln file.

After the last step, the unidentified files that were changed to the measurements category beforehand are visible in the project view. However, in the measurements table, the "unidentified-> measurement" files are not present anymore. They are also not present in the unidentified table.

Verification gives messages of this kind:
dch11: image not in measurement m-032405082ae74f07b751ac62d090bb5a

 [Example .eln file, where a single unidentified file (.lext) was changed to measurement category](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu/download?path=%2F&files=Issue_79_example.eln)

[Issue 79 full log](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu/download?path=%2F&files=Issue_79_full%20log)

**Comment by SteffenBrinckmann** [comment]
Also difficult to believe (he missing image of an unidentified item is the issue) it is the same as #76 
fixed in PR #90

**Comment by HTsybenko** [comment]
Cannot verify the fix due to the existing bugs in #107 and #114.

**Comment by HTsybenko** [comment]
The "unidentified-> measurement" files remain intact after the eln file import.
