### ISSUE TITLE
Heading styles in project view

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#84]
While headings are displayed properly in the project description field, for folders and other items in the project view, those are displayed always in the same style, even though three options are available.

![Screenshot from 2023-10-13 15-23-59](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/7ef101ff-605e-4d49-886d-908d9220672b)

**Comment by SteffenBrinckmann** [comment]
That is true and to be like that. We can discuss the reason in a meeting on design.

**Comment by SteffenBrinckmann** [comment]
And yes it is not consistent.

**Comment by HTsybenko** [comment]
The headings are displayed correctly in the project description field and for individual items.
