### ISSUE TITLE
Permanent project view

### ISSUE THREAD

**Issue by SteffenBrinckmann** [PASTA-ELN/pasta-eln#95]
Save into database and use
- "is a folder expanded or not"
- "is an item minimized"

**Comment by HTsybenko** [comment]
Another small change related to Visibility options that can go to 2.6:
Most visibility options would automatically change from "Hide" to "Show"  when selected.

The only option which does not change correspondingly is  in the item editing window (double click on the item in the project view or table view). When right clicking on the image in the editing window, it gives "Hide" option, but if the item is hidden, it would still be "Hide". 

You can also use "Invert hidden status" here, as you do in the table view.

**Comment by HTsybenko** [comment]
All the Project view visibility options are permanently saved, except for the "Hide/show project details".

**Comment by SteffenBrinckmann** [comment]
I did not think of that since the project is special (its the master) in the project view. Now fixed, 2.5.0b6
