### ISSUE TITLE
Display of comments in views

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#98]
The display of the comments in the table view is not consistent.

1) Single-line text comments are displayed as simple text similar to the Tags and links to Samples and Procedures.
Even if the comment text has Markdown styling, it will not be shown.
The text cannot be selected, selecting it only works when one opens the item to edit in a new window.

Example:
![Screenshot from 2023-10-16 13-31-53](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/4fd6b399-60c8-406b-a393-45f2d0fbba87)

![Screenshot from 2023-10-16 13-29-54](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/70a4e854-2456-43e7-9788-fe492db8da15)

2) When the comment has several paragraphs (lines separated with an “Enter”), it will be displayed in a new white field, and the Markdown styling will be applied.
The comment white field, however, has a fixed size and is not scaling correctly with the width of the left column.
The text can be selected.

Example:
![Screenshot from 2023-10-16 13-32-10](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/21053b18-93bd-495c-a6be-766999a0029d)

![Screenshot from 2023-10-16 13-32-28](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/7a862f30-4f58-4fa4-9b7d-a8a6eb7c6316)

**Comment by SteffenBrinckmann** [comment]
- Adopt height to number of lines
- adjust the width
- make selectable ? Check why / possible

**Comment by HTsybenko** [comment]
The display of comments is still a bit inconsistent:
1) One-liner comments do not allow text styles to be applied:

![Screenshot from 2023-10-27 11-33-01](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/fccef6a4-aa22-419e-a881-2f4cf0ec650d)

The text is not selectable and the width of the comment field does not adjust to the width of the right side:

![Screenshot from 2023-10-27 11-35-08](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/64a7706e-472f-40c2-84f2-c4add47e5171)



2) Multi-liners can be selected, styles are applied, but the width of the field is also constrained:

![Screenshot from 2023-10-27 11-34-04](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/8801c46e-727a-4209-86ef-3e904f44b999)

**Comment by SteffenBrinckmann** [comment]
Ok, the selection and one-line issue I have fixed. But I cannot understand why the 'field is constrained'. The same code works in project view and does not constrain in the comment in the  head there. After 40min of running with my head against some wall, ... some other day
