### ISSUE TITLE
Deleting "Comment" in Ontology editor

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#99]
1) Open "Ontology Editor"
2) In the opened window (Structure 0), click on deleting the “comment” property.

   A message occurs:
/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py:131: RuntimeWarning: Invalid return value in function QAbstractTableModel.flags, expected PySide6.QtCore.Qt.ItemFlags, got NoneType.
  self.triggered.connect(lambda : widget.execute(command))

3) If saved after that, another warning appears:
/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/ontology_configuration/ontology_configuration_extended.py:434: RuntimeWarning: Invalid return value in function QAbstractTableModel.flags, expected PySide6.QtCore.Qt.ItemFlags, got NoneType.

Log:
10-16 09:13:00|INFO:Start PASTA GUI
10-16 09:13:00|INFO:End PASTA GUI
10-16 09:13:04|INFO:Setting up slots for the editor..
10-16 09:13:04|INFO:User loaded the ontology data in UI
10-16 09:13:04|INFO:New type selected in UI: {Structure level 0}
10-16 09:13:04|INFO:Table Data updated..
10-16 09:13:04|INFO:Table Data updated..
10-16 09:13:04|INFO:Table Data updated..
10-16 09:13:04|INFO:New property category selected in UI: {default}
10-16 09:13:04|INFO:Table Data updated..
10-16 09:13:06|INFO:Delete signal emitted for the position: {4}
10-16 09:13:06|INFO:Deleted (row: {4}, data: {{'name': 'comment', 'query': '#tags comments remarks :field:value:'}})…

**Comment by jmurugan-fzj** [comment]
@HTsybenko I have observed this also multiple times, but the functionality as such will not be affected by the error, deletion would succeed right or do you see any actual issue also associated with this error message?
